export declare const API_VERSION = 1;
export declare const API_BASE_NEAR_MAINNET = "https://mintbase.hasura.app/v1/graphql";
export declare const API_BASE_NEAR_TESTNET = "https://mintbase.hasura.app/v1/graphql";
export declare const BASE_ARWEAVE_URI = "https://arweave.net";
export declare const CLOUD_BASE_URI = "https://us-central1-omni-base-1.cloudfunctions.net";
export declare const CLOUD_GET_FILE_METADATA_URI: (fileName: string) => string;
export declare const CLOUD_POST_METADATA_URI: () => string;
export declare const DEFAULT_APP_NAME = "Mintbase.js";
export declare const NEAR_LOCAL_STORAGE_KEY_SUFFIX = "_wallet_auth_key";
export declare const STORE_FACTORY_CONTRACT_NAME: string;
export declare const MARKET_ACCOUNT: string;
export declare const STORE_CONTRACT_VIEW_METHODS: string[];
export declare const STORE_CONTRACT_CALL_METHODS: string[];
export declare const CLOUD_STORAGE_CONFIG: {
    apiKey: string | undefined;
    authDomain: string | undefined;
    databaseURL: string | undefined;
    projectId: string | undefined;
    storageBucket: string | undefined;
};
