import type { NextPage } from 'next';
import Head from 'next/head';
import { useMintbaseSession, useWallet } from '@mintbase-js/react';
import { TokenExample } from '../components/TokenExample';
import { TransferTest } from '../components/TransferTest';
import styles from '../styles/Home.module.css';
import { getAuth, signInWithCustomToken } from 'firebase/auth';
import { useEffect } from 'react';

// Import the functions you need from the SDKs you need
import { initializeApp } from 'firebase/app';
// import { getAnalytics } from 'firebase/analytics';
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: 'AIzaSyAwZOiBAke2iUnLPp-hf4-uUKbL6lhaY0I',
  authDomain: 'omni-live.firebaseapp.com',
  projectId: 'omni-live',
  storageBucket: 'omni-live.appspot.com',
  messagingSenderId: '121691574728',
  appId: '1:121691574728:web:42884cdb2e6ca58274b0fd',
  measurementId: 'G-XD6G6HW6M6',
};

// Initialize Firebase
initializeApp(firebaseConfig);
// const analytics = getAnalytics(app);

const Home: NextPage = () => {
  const {
    connect,
    disconnect,
    activeAccountId,
    isWaitingForConnection,
    isWalletSelectorSetup,
  } = useWallet();

  const {
    session,
    error: sessionError,
    requestSession,
  } = useMintbaseSession();


  const testFirebaseLogin = async (): Promise<void> => {
    const auth = getAuth();
    const login = await signInWithCustomToken(auth, session.token);
    console.log('has firebase login!', login);
  };
  useEffect(() => {
    if (!session) {
      return;
    }
    void testFirebaseLogin();
  }, [session]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Mintbase SDK Next Test Suite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Mintbase SDK</h1>
        <h3>NextJS Test Suite</h3>

        <p className={styles.description}>
          This is a test suite for development and testing with NextJS.
          <br />
        </p>

        {isWaitingForConnection ? (
          <div>Waiting for a wallet connection...</div>
        ) : null}

        {isWalletSelectorSetup ? (
          <div>
            {activeAccountId ? (
              <div className={styles.description}>
                <h2>You are logged in as {activeAccountId}</h2>
                <button className={styles.button} onClick={disconnect}>
                  DISCONNECT
                </button>
              </div>
            ) : (
              <div className={styles.description}>
                <h2>To continue, login with NEAR</h2>
                <button className={styles.button} onClick={connect}>
                  CONNECT
                </button>
              </div>
            )}
          </div>
        ) : (
          <div>Waiting for wallet selector components...</div>
        )}

        {(activeAccountId && !session) ? (
          <button className={styles.button} onClick={requestSession}>
            REQUEST MINTBASE SESSION
          </button>
        ) : null}

        {session
          ? <p>A mintbase session is active for {session.accountId}, created {session.createdAt}</p>
          : <p>No mintbase session yet</p>
        }

        {sessionError
          ? <p>Error starting session: {sessionError}</p>
          : null
        }

        <h2>Test Components</h2>
        {activeAccountId ? <TransferTest /> : null}

        <TokenExample />
      </main>

      <footer className={styles.footer}>
        <a href="http://mintbase.io">Mintbase</a>
      </footer>
    </div>
  );
};

export default Home;
