name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npx lerna bootstrap --no-ci --force-local
      - run: npm run lint
      - run: npm run build
      - run: npm run test

  coverage:
    needs:
      - build
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate LCOV results
        uses: RauliL/lerna-lcov-aggregate-action@master

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}