name: Build and Publish Docs

on:
  release:
    types: [released]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Configure git
        run: |
          git config --global user.name "mintbaseteam"
          git config --global user.email "eng@mintbase.io"

      - name: Publish Docs
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: npm run docs
