name: Telegram P/R Open notification

on:
  issues:
   types: [opened, edited, milestoned]


jobs:
  open-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ISSUE_CHAT }}
          token: ${{ secrets.TELEGRAM_ISSUE_TOKEN }}
          format: markdown
          message: |
            [mintbase.js](https://github.com/Mintbase/mintbase-js/issues/) ➡️ [OPEN] [${{ github.event.issue.title }}](${{ github.event.pull_request.html_url }}) by ${{ github.actor }}