name: Telegram P/R Open notification

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  open-pr:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the telegram notify action to send a notification
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            [omni-site](https://github.com/Mintbase/omni-site/pull/) ➡️ [OPEN] [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}) by ${{ github.actor }}
            Commit message: ${{ github.event.head_commit.message }}
            [Testnet Environment](https://omni-site-git-${{github.head_ref}}-mintbase.vercel.app)
