name: Slack P/R Request Changes notification

on:
  pull_request_review:
    types: [submitted]

jobs:
  changesrequested:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the Slack webhook notify action to send a notification
      - name: Slack Notify
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: 'github-flows'
          payload: |
            {
              "text": "♻️ [REQUESTED CHANGES] : <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\nBy:${{ github.actor }} "
            }
