name: Publish Packages to NPM

on:
  release:
    types: [released, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Configure git and npm creds
        run: |
          git config --global user.name "mintbaseteam"
          git config --global user.email "eng@mintbase.io"
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_MINTBASEJS_AUTH_TOKEN }}"

      - name: Build & Test
        run: |
          npm ci
          npm run bootstrap
          npm run build
          npm run test

      - name: Version, Publish and Push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lerna version ${{ github.event.release.tag_name }} --yes --skip-git
          git add --all
          git commit -m "Release ${{ github.event.release.tag_name }}"
          lerna publish from-package --yes
          git push
