name: npm-publish-rc

#on:
#  push:
#    branches:
#      - main # Change this to your default branch

on:
  release:
    types: [released, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commit }}

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Configure git and npm Credentials
        run: |
          git config --global user.name "mintbaseteam"
          git config --global user.email "eng@mintbase.io"
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_MINTBASEJS_AUTH_TOKEN }}"

      - name: Build & Test
        run: |
          npm install
          npm run build
          npm run test

      - name: Bump Version & Commit
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lerna version ${{ github.event.release.tag_name }} --yes
          git push

      - name: Publish Pre Released
        if: ${{ github.even.release.type.prereleased }}
        run: |
          lerna publish --dist-tag rc --yes


